version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./php-service:/php-service
            - ./config/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - webapp-network
    php:
        build:
            context: .
            dockerfile: dockerfile-php-service
        image: sp-grpc-test/php-service
        volumes:
            - ./php-service:/php-service
            - ./config/php.ini:/usr/local/etc/php/php.ini
        networks:
            - webapp-network
            - service-network

    hello-world:
        build:
            context: .
            dockerfile: dockerfile-hello-world-service
        image: sp-grpc-test/hello-world-service
        volumes:
            - ./hello-world-service:/hello-world-service
        ports:
            - "50051:50051"
        networks:
            - service-network
        tty: true
networks:
    webapp-network:
        driver: bridge
    service-network:
        driver: bridge
